# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-05 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attributes_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_a', models.CharField(max_length=255)),
                ('attribute_b', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('map_id', models.CharField(max_length=30)),
                ('link_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Kind_num', models.CharField(max_length=255)),
                ('Kind', models.CharField(max_length=30)),
                ('Width', models.CharField(max_length=255)),
                ('Direction', models.CharField(max_length=255)),
                ('Toll', models.CharField(max_length=255)),
                ('Const_St', models.CharField(max_length=255)),
                ('UndConCRID', models.CharField(max_length=255)),
                ('FuncClass', models.CharField(max_length=255)),
                ('Length', models.CharField(max_length=255)),
                ('DetailCity', models.CharField(max_length=255)),
                ('Through', models.CharField(max_length=255)),
                ('UnThruCRID', models.CharField(max_length=13)),
                ('Ownership', models.CharField(max_length=255)),
                ('Road_Cond', models.CharField(max_length=255)),
                ('Special', models.CharField(max_length=255)),
                ('AdminCodeL', models.CharField(max_length=30)),
                ('AdminCodeR', models.CharField(max_length=30)),
                ('Uflag', models.CharField(max_length=255)),
                ('OnewayCRID', models.CharField(max_length=30)),
                ('AccessCRID', models.CharField(max_length=30)),
                ('SpeedClass', models.CharField(max_length=255)),
                ('LaneNumS2E', models.CharField(max_length=30)),
                ('LaneNumE2S', models.CharField(max_length=30)),
                ('LaneNum', models.CharField(max_length=255)),
                ('Vehcl_Type', models.CharField(max_length=255)),
                ('Elevated', models.CharField(max_length=255)),
                ('Structure', models.CharField(max_length=255)),
                ('UseFeeCRID', models.CharField(max_length=30)),
                ('UseFeeType', models.CharField(max_length=255)),
                ('SpdLmtS2E', models.CharField(max_length=30)),
                ('SpdLmtE2S', models.CharField(max_length=30)),
                ('SpdSrcS2E', models.CharField(max_length=255)),
                ('SpdSrcE2S', models.CharField(max_length=255)),
                ('DC_Type', models.CharField(max_length=255)),
                ('NoPassCRID', models.CharField(max_length=30)),
                ('OutBanCRID', models.CharField(max_length=30)),
                ('NumBanCRID', models.CharField(max_length=30)),
                ('ParkFlag', models.CharField(max_length=255)),
                ('points', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='link_attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('time', models.DateTimeField()),
                ('time_related', models.BooleanField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Matched_GPS',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(max_length=255)),
                ('matched_num', models.IntegerField()),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.Link')),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('grid', models.CharField(max_length=255)),
                ('poi_id', models.AutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=255)),
                ('chain_code', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=255)),
                ('admin_code', models.CharField(max_length=255)),
                ('vadmin_code', models.CharField(max_length=255)),
                ('lon', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=255)),
                ('importance', models.CharField(max_length=255)),
                ('prior_auth', models.CharField(max_length=255)),
                ('side', models.CharField(max_length=255)),
                ('pid', models.CharField(max_length=255)),
                ('tel_type', models.CharField(max_length=255)),
                ('poi_flag', models.CharField(max_length=255)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.Link')),
            ],
        ),
        migrations.CreateModel(
            name='SE_node',
            fields=[
                ('grid', models.CharField(max_length=255)),
                ('node_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('links_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubMap',
            fields=[
                ('map_id', models.CharField(max_length=30)),
                ('submap_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('valid_dist', models.CharField(max_length=255)),
                ('pre_dist', models.CharField(max_length=255)),
                ('cr_id', models.CharField(max_length=255)),
                ('in_link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.Link')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiskEvaluation.SE_node')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='EnodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ENode', to='RiskEvaluation.SE_node'),
        ),
        migrations.AddField(
            model_name='link',
            name='SnodeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SNode', to='RiskEvaluation.SE_node'),
        ),
    ]
