# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RiskEvaluation', '0002_delete_submap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link_attributes',
            old_name='attribute',
            new_name='lane_num',
        ),
        migrations.RemoveField(
            model_name='link_attributes',
            name='time',
        ),
        migrations.RemoveField(
            model_name='link_attributes',
            name='time_related',
        ),
        migrations.RemoveField(
            model_name='link_attributes',
            name='value',
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='lane_width',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='mixed_traffic',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='radius',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='speed_limit',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='trrafic_sign',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
