# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiskEvaluation', '0003_auto_20170423_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='link_attributes',
            name='poi_importance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='link_attributes',
            name='poi_num',
            field=models.IntegerField(default=0),
        ),
    ]
